import type { Garment } from "./types";

/** Seed wardrobe so the product feels complete before commerce sync. */
export function seedWardrobe(userId: string): Garment[] {
  const now = new Date().toISOString();
  const base: Omit<Garment, "id" | "userId" | "createdAt" | "updatedAt">[] = [
    {
      name: "Ivory Ribbed Quarter-Zip",
      brand: "Aether Edit",
      category: "top",
      colors: ["ivory"],
      hexColors: ["#F5F0E6"],
      fabric: "ribbed knit",
      texture: "ribbed",
      formality: "smart_casual",
      season: ["autumn", "winter", "all"],
      imageUrl:
        "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600&q=80",
      source: "manual",
      tags: ["quiet luxury", "knit"],
    },
    {
      name: "Tailored Charcoal Trousers",
      brand: "Aether Tailoring",
      category: "bottom",
      colors: ["charcoal"],
      hexColors: ["#36454F"],
      fabric: "wool",
      texture: "smooth",
      formality: "business",
      season: ["all"],
      imageUrl:
        "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&q=80",
      source: "manual",
      tags: ["old money", "tailored"],
    },
    {
      name: "Stone Wide Pleat Trousers",
      brand: "Studio Forme",
      category: "bottom",
      colors: ["stone"],
      hexColors: ["#C2B8A3"],
      fabric: "cotton twill",
      texture: "matte",
      formality: "smart_casual",
      season: ["spring", "summer", "autumn"],
      imageUrl:
        "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&q=80",
      source: "manual",
      tags: ["relaxed", "old money"],
    },
    {
      name: "Midnight Navy Blazer",
      brand: "Harris & Stone",
      category: "outerwear",
      colors: ["navy"],
      hexColors: ["#1B2A41"],
      fabric: "wool",
      texture: "structured",
      formality: "formal",
      season: ["all"],
      imageUrl:
        "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&q=80",
      source: "manual",
      tags: ["boardroom", "formal"],
    },
    {
      name: "White Oxford Shirt",
      brand: "Aether Basics",
      category: "top",
      colors: ["white"],
      hexColors: ["#FFFFFF"],
      fabric: "cotton",
      texture: "poplin",
      formality: "business",
      season: ["all"],
      imageUrl:
        "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=600&q=80",
      source: "manual",
      tags: ["classic"],
    },
    {
      name: "Ribbed Indigo Jeans",
      brand: "Denim Atelier",
      category: "bottom",
      colors: ["indigo"],
      hexColors: ["#3F4C6B"],
      fabric: "denim",
      texture: "ribbed denim",
      formality: "casual",
      season: ["all"],
      imageUrl:
        "https://images.unsplash.com/photo-1542272454315-7f6b1807cdfd?w=600&q=80",
      source: "manual",
      tags: ["casual", "denim"],
    },
    {
      name: "Cognac Leather Loafers",
      brand: "London Last",
      category: "shoes",
      colors: ["cognac"],
      hexColors: ["#8B5A2B"],
      fabric: "leather",
      texture: "polished",
      formality: "business",
      season: ["all"],
      imageUrl:
        "https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=600&q=80",
      source: "manual",
      tags: ["footwear", "old money"],
    },
    {
      name: "Suede Chelsea Boots",
      brand: "North Bridge",
      category: "shoes",
      colors: ["taupe"],
      hexColors: ["#8B7E66"],
      fabric: "suede",
      texture: "suede",
      formality: "smart_casual",
      season: ["autumn", "winter"],
      imageUrl:
        "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=600&q=80",
      source: "manual",
      tags: ["boots"],
    },
    {
      name: "Gold Rimless Frames",
      brand: "Optique",
      category: "accessory",
      colors: ["gold"],
      hexColors: ["#C9A87C"],
      fabric: "metal",
      texture: "brushed metal",
      formality: "smart_casual",
      season: ["all"],
      imageUrl:
        "https://images.unsplash.com/photo-1574258495973-f010dfbb5147?w=600&q=80",
      source: "manual",
      tags: ["frames", "metallic sync"],
    },
    {
      name: "Camel Overcoat",
      brand: "Aether Outer",
      category: "outerwear",
      colors: ["camel"],
      hexColors: ["#C19A6B"],
      fabric: "wool cashmere",
      texture: "brushed",
      formality: "formal",
      season: ["autumn", "winter"],
      imageUrl:
        "https://images.unsplash.com/photo-1544923246-77307dd654cb?w=600&q=80",
      source: "manual",
      tags: ["coat", "old money"],
    },
  ];

  return base.map((item, i) => ({
    ...item,
    id: `seed_${i + 1}`,
    userId,
    createdAt: now,
    updatedAt: now,
  }));
}
