import type { Garment } from "./types";

/** Bump to force-refresh local seed wardrobe images/labels. */
export const WARDROBE_SEED_VERSION = 11;

/**
 * Controlled local garment images — names, colors, and files must match.
 * Paths are served from /public/garments and converted to data URLs for fal try-on.
 */
export function seedWardrobe(userId: string): Garment[] {
  const now = new Date().toISOString();
  const base: Omit<Garment, "id" | "userId" | "createdAt" | "updatedAt">[] = [
    {
      name: "White Oxford Shirt",
      brand: "VoiceDress Basics",
      category: "top",
      colors: ["white"],
      hexColors: ["#FFFFFF"],
      fabric: "cotton",
      texture: "poplin",
      formality: "business",
      season: ["all"],
      imageUrl: "/garments/white-oxford.jpg",
      source: "manual",
      tags: ["classic", "white"],
    },
    {
      name: "Tailored Charcoal Trousers",
      brand: "VoiceDress Tailoring",
      category: "bottom",
      colors: ["charcoal", "dark grey"],
      hexColors: ["#2F343A"],
      fabric: "wool",
      texture: "smooth",
      formality: "business",
      season: ["all"],
      imageUrl: "/garments/charcoal-trousers.jpg",
      source: "manual",
      tags: ["old money", "tailored", "charcoal"],
    },
    {
      name: "Ivory Ribbed Quarter-Zip",
      brand: "VoiceDress Edit",
      category: "top",
      colors: ["ivory"],
      hexColors: ["#F5F0E6"],
      fabric: "ribbed knit",
      texture: "ribbed",
      formality: "smart_casual",
      season: ["autumn", "winter", "all"],
      imageUrl: "/garments/ivory-quarterzip.jpg",
      source: "manual",
      tags: ["quiet luxury", "knit"],
    },
    {
      name: "Stone Wide Pleat Trousers",
      brand: "Studio Forme",
      category: "bottom",
      colors: ["stone", "khaki"],
      hexColors: ["#C2B8A3"],
      fabric: "cotton twill",
      texture: "matte",
      formality: "smart_casual",
      season: ["spring", "summer", "autumn"],
      imageUrl: "/garments/stone-trousers.jpg",
      source: "manual",
      tags: ["relaxed", "stone"],
    },
    {
      name: "Midnight Navy Blazer",
      brand: "Harris & Stone",
      category: "outerwear",
      colors: ["navy"],
      hexColors: ["#1B2A41"],
      fabric: "wool",
      texture: "structured",
      formality: "formal",
      season: ["all"],
      imageUrl: "/garments/navy-blazer.jpg",
      source: "manual",
      tags: ["boardroom", "formal"],
    },
    {
      name: "Ribbed Indigo Jeans",
      brand: "Denim Atelier",
      category: "bottom",
      colors: ["indigo", "blue"],
      hexColors: ["#3F4C6B"],
      fabric: "denim",
      texture: "ribbed denim",
      formality: "casual",
      season: ["all"],
      imageUrl: "/garments/indigo-jeans.jpg",
      source: "manual",
      tags: ["casual", "denim"],
    },
    {
      name: "Cognac Leather Loafers",
      brand: "London Last",
      category: "shoes",
      colors: ["cognac", "brown"],
      hexColors: ["#8B5A2B"],
      fabric: "leather",
      texture: "polished",
      formality: "business",
      season: ["all"],
      imageUrl: "/garments/cognac-loafers.jpg",
      source: "manual",
      tags: ["footwear", "old money"],
    },
    {
      name: "Suede Chelsea Boots",
      brand: "North Bridge",
      category: "shoes",
      colors: ["taupe", "sandy brown", "light brown"],
      hexColors: ["#C4A882", "#8B7E66"],
      fabric: "suede",
      texture: "suede nap",
      formality: "smart_casual",
      season: ["autumn", "winter"],
      imageUrl: "/garments/chelsea-boots.jpg",
      source: "manual",
      tags: ["boots", "taupe", "chelsea"],
    },
    {
      name: "Gold Rimless Frames",
      brand: "Optique",
      category: "accessory",
      colors: ["gold"],
      hexColors: ["#C9A87C"],
      fabric: "metal",
      texture: "brushed metal",
      formality: "smart_casual",
      season: ["all"],
      imageUrl: "/garments/gold-frames.jpg",
      source: "manual",
      tags: ["frames", "eyeglasses"],
    },
    {
      name: "Silver Link Watch",
      brand: "VoiceDress Time",
      category: "accessory",
      colors: ["silver"],
      hexColors: ["#C0C0C0"],
      fabric: "steel",
      texture: "brushed steel",
      formality: "smart_casual",
      season: ["all"],
      imageUrl: "/garments/silver-watch.jpg",
      source: "manual",
      tags: ["watch", "wristwatch"],
    },
    {
      name: "Camel Overcoat",
      brand: "VoiceDress Outer",
      category: "outerwear",
      colors: ["camel"],
      hexColors: ["#C19A6B"],
      fabric: "wool cashmere",
      texture: "brushed",
      formality: "formal",
      season: ["autumn", "winter"],
      imageUrl: "/garments/camel-overcoat.jpg",
      source: "manual",
      tags: ["coat", "old money"],
    },
  ];

  return base.map((item, i) => ({
    ...item,
    id: `seed_v${WARDROBE_SEED_VERSION}_${i + 1}`,
    userId,
    createdAt: now,
    updatedAt: now,
  }));
}

export function isSeedWardrobe(items: Garment[]) {
  return (
    items.length > 0 &&
    items.every((g) => g.id.startsWith("seed_") || g.id.startsWith("seed_v"))
  );
}
